server {
  listen 80;
  server_name sd2.youdooart.com;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/html;
  }

  location / {
    return 301 https://sd2.youdoodesign.com$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name sd2.youdooart.com;

  ssl_certificate /etc/letsencrypt/live/sd2.youdooart.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/sd2.youdooart.com/privkey.pem;

  add_header Cache-Control no-store always;
  return 301 https://sd2.youdoodesign.com$request_uri;
}
