import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { prisma } from '../src/lib/prisma';
import { submitStudioBatch, listStudioTasks, parseStudioRequest, finishStudioTask } from '../src/lib/image-studio/tasks';
import { getImageStudioSettings, saveImageStudioSettings } from '../src/lib/image-studio/settings';
import { processStudioTask, recoverStudioTasks } from '../src/lib/image-studio/worker';

async function main() {
  if (!process.env.DATABASE_URL?.startsWith('file:/tmp/sd2-image-studio-test-')) throw new Error('Use an isolated /tmp/sd2-image-studio-test-* database');
  const working = await fs.mkdtemp(path.join(os.tmpdir(), 'sd2-image-studio-fixture-'));
  process.chdir(working);
  const user = await prisma.user.create({ data: { id: 'image-test-owner', name: 'Test', username: 'image-test-owner', email: 'image-test@example.invalid', password_hash: 'not-a-login-password' } });
  const stranger = await prisma.user.create({ data: { id: 'image-test-other', name: 'Test2', username: 'image-test-other', email: 'image-other@example.invalid', password_hash: 'not-a-login-password' } });
  await prisma.creditAccount.create({ data: { user_id: user.id, balance: 20 } });
  await prisma.platformSetting.create({ data: { key: 'musk_api_v1', value_json: JSON.stringify({ enabled: true, base_url: 'https://example.invalid/', api_key: 'test-only', default_model: 'gpt-5.5' }) } });
  const initial = await getImageStudioSettings();
  const config = await saveImageStudioSettings({ ...initial, context: 'Fixed studio context', prices: { 'gpt-image-2.5-flare': 2, 'gpt-image-2.5-sunburst': null } }, user.id);
  assert.ok(config);
  assert.equal(await saveImageStudioSettings(initial, user.id), null, 'stale revision must conflict');
  const input = { requestId: 'test-request-12345678', prompt: 'Draw a square', count: 2, revision: config.revision, referenceIds: [] };
  const batch = await submitStudioBatch(user.id, input);
  assert.equal(await submitStudioBatch(user.id, input), batch, 'duplicate request must reuse tasks');
  assert.equal(await prisma.imageStudioTask.count(), 2);
  assert.equal((await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } })).frozen_credits, 4);
  await assert.rejects(submitStudioBatch(user.id, { ...input, prompt: 'changed' }));
  await assert.rejects(submitStudioBatch(user.id, { ...input, requestId: 'another-request-1234', referenceIds: ['not-owned'] }));
  assert.throws(() => parseStudioRequest({ ...input, count: 9 }));
  assert.throws(() => parseStudioRequest({ ...input, referenceIds: ['a', 'b', 'c'] }));
  await saveImageStudioSettings({ ...config, context: 'New context' }, user.id);
  const png = await sharp({ create: { width: 4, height: 4, channels: 3, background: '#ff0000' } }).png().toBuffer();
  await processStudioTask(async args => {
    assert.equal(args.count, 1);
    assert.ok(args.prompt.startsWith('Fixed studio context'), 'task must retain submitted context');
    return { images: [png.toString('base64')], usage: { total_tokens: 10 } };
  });
  await processStudioTask(async () => { throw new Error('mock transport failure'); });
  const account = await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } });
  assert.equal(account.balance, 18); assert.equal(account.frozen_credits, 0);
  const succeeded = await prisma.imageStudioTask.findFirstOrThrow({ where: { status: 'succeeded' } });
  await finishStudioTask(succeeded, 'succeeded');
  assert.equal((await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } })).balance, 18, 'settlement cannot run twice');
  const own = await listStudioTasks(user.id);
  assert.equal(own.tasks.length, 2);
  assert.ok(!('context' in own.tasks[0]));
  assert.equal((await listStudioTasks(stranger.id)).tasks.length, 0);
  assert.ok(own.tasks.find(task => task.status === 'succeeded')?.asset?.original_url);
  const latest = await getImageStudioSettings();
  await submitStudioBatch(user.id, { ...input, count: 1, requestId: 'expired-request-1234', revision: latest.revision });
  await prisma.imageStudioTask.updateMany({ where: { status: 'queued' }, data: { status: 'running', lease_token: 'expired-test', lease_until: new Date(0) } });
  await recoverStudioTasks(); await recoverStudioTasks();
  const recovered = await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } });
  assert.equal(recovered.balance, 18); assert.equal(recovered.frozen_credits, 0);
  assert.equal(await prisma.creditLedger.count({ where: { type: 'task_success_deduct' } }), 1);
  console.log('PASS: immutable context, idempotent submit/settlement, per-image charging/refund, owner isolation, stale-setting conflict, expired lease recovery, saved PNG. No network generation.');
  await prisma.$disconnect();
}
void main().catch(async error => { console.error(error); await prisma.$disconnect(); process.exitCode = 1; });
