import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { randomUUID } from 'node:crypto';
import { prisma } from '../src/lib/prisma';
import { submitStudioBatch, listStudioTasks, parseStudioRequest, finishStudioTask, deleteStudioResult } from '../src/lib/image-studio/tasks';
import { changeStudioRatio, listStudioRatios } from '../src/lib/image-studio/ratio-preferences';
import { getImageStudioSettings, saveImageStudioSettings } from '../src/lib/image-studio/settings';
import { processStudioTask, recoverStudioTasks } from '../src/lib/image-studio/worker';
import { defaultStudioModuleId, listStudioModules, saveStudioModule } from '../src/lib/image-studio/modules';

async function main() {
  if (!process.env.DATABASE_URL?.startsWith('file:/tmp/sd2-image-studio-test-')) throw new Error('Use an isolated /tmp/sd2-image-studio-test-* database');
  const working = await fs.mkdtemp(path.join(os.tmpdir(), 'sd2-image-studio-fixture-'));
  process.chdir(working);
  const user = await prisma.user.create({ data: { id: 'image-test-owner', name: 'Test', username: 'image-test-owner', email: 'image-test@example.invalid', password_hash: 'not-a-login-password' } });
  const stranger = await prisma.user.create({ data: { id: 'image-test-other', name: 'Test2', username: 'image-test-other', email: 'image-other@example.invalid', password_hash: 'not-a-login-password' } });
  await prisma.creditAccount.create({ data: { user_id: user.id, balance: 20 } });
  await prisma.platformSetting.create({ data: { key: 'image_generation_api_v1', value_json: JSON.stringify({ enabled: true, provider: 'musk', base_url: 'https://example.invalid/', api_key: 'test-only', default_model: 'gemini-3.1-flash-image-preview' }) } });
  const initial = await getImageStudioSettings();
  const config = await saveImageStudioSettings({ ...initial, context: 'Fixed studio context', prices: { ...initial.prices, 'gemini-3.1-flash-image-preview': 2, 'gpt-image-2.5-flare': 2, 'gpt-image-2.5-sunburst': null } }, user.id);
  assert.ok(config);
  assert.equal(await saveImageStudioSettings(initial, user.id), null, 'stale revision must conflict');
  const input = { requestId: 'test-request-12345678', prompt: 'Draw a square', count: 2, revision: config.revision, referenceIds: [] };
  const batch = await submitStudioBatch(user.id, input);
  assert.equal(await submitStudioBatch(user.id, input), batch, 'duplicate request must reuse tasks');
  assert.equal(await prisma.imageStudioTask.count(), 2);
  assert.equal((await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } })).frozen_credits, 4);
  await assert.rejects(submitStudioBatch(user.id, { ...input, prompt: 'changed' }));
  await assert.rejects(submitStudioBatch(user.id, { ...input, requestId: 'another-request-1234', referenceIds: ['not-owned'] }));
  assert.throws(() => parseStudioRequest({ ...input, count: 9 }));
  assert.throws(() => parseStudioRequest({ ...input, referenceIds: Array.from({ length: 11 }, () => 'a') }));
  assert.equal(parseStudioRequest({ ...input, referenceIds: Array.from({ length: 10 }, (_, index) => `asset-${index}`) }).referenceIds.length, 10);
  await saveImageStudioSettings({ ...config, context: 'New context' }, user.id);
  const png = await sharp({ create: { width: 4, height: 4, channels: 3, background: '#ff0000' } }).png().toBuffer();
  await processStudioTask(async args => {
    assert.equal(args.count, 1);
    assert.ok(args.prompt.startsWith('Fixed studio context'), 'task must retain submitted context');
    return { images: [png.toString('base64')], usage: { total_tokens: 10 } };
  });
  await processStudioTask(async () => { throw new Error('mock transport failure'); });
  const account = await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } });
  assert.equal(account.balance, 18); assert.equal(account.frozen_credits, 0);
  const succeeded = await prisma.imageStudioTask.findFirstOrThrow({ where: { status: 'succeeded' } });
  await finishStudioTask(succeeded, 'succeeded');
  assert.equal((await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } })).balance, 18, 'settlement cannot run twice');
  const own = await listStudioTasks(user.id);
  assert.equal(own.tasks.length, 2);
  assert.ok(!('context' in own.tasks[0]));
  assert.equal((await listStudioTasks(stranger.id)).tasks.length, 0);
  assert.ok(own.tasks.find(task => task.status === 'succeeded')?.asset?.original_url);
  const latest = await getImageStudioSettings();
  await submitStudioBatch(user.id, { ...input, count: 1, requestId: 'expired-request-1234', revision: latest.revision });
  await prisma.imageStudioTask.updateMany({ where: { status: 'queued' }, data: { status: 'running', lease_token: 'expired-test', lease_until: new Date(0) } });
  await recoverStudioTasks(); await recoverStudioTasks();
  const recovered = await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } });
  assert.equal(recovered.balance, 18); assert.equal(recovered.frozen_credits, 0);
  assert.equal(await prisma.creditLedger.count({ where: { type: 'task_success_deduct' } }), 1);
  assert.throws(() => parseStudioRequest({ ...input, prompt: '  ', referenceIds: [] }));
  assert.equal(parseStudioRequest({ ...input, prompt: '', referenceIds: ['image'] }).prompt, '');
  const moduleId = randomUUID();
  const created = await saveStudioModule(user.id, { id: moduleId }, true);
  const moduleBody = { id: moduleId, revision: created.revision, name: 'Saved module', prompt: '', count: 1, aspectRatio: '5:3', model: 'gpt-image-2.5-sunburst', prices: { ...config.prices, 'gpt-image-2.5-flare': 7, 'gpt-image-2.5-sunburst': 9 }, referenceIds: [], context: 'Module context' };
  const ordinarySaved = await saveStudioModule(user.id, { ...moduleBody, model: 'gpt-image-2.5-flare', prices: undefined });
  assert.equal(ordinarySaved.context, 'Module context');
  assert.equal(ordinarySaved.model, 'gpt-image-2.5-flare');
  assert.equal(ordinarySaved.unitCredits, 2);
  const saved = await saveStudioModule(user.id, { ...moduleBody, revision: ordinarySaved.revision }, false, true);
  assert.equal(saved.aspectRatio, '5:3');
  assert.equal(saved.model, 'gpt-image-2.5-sunburst');
  assert.equal(saved.unitCredits, 9);
  await assert.rejects(saveStudioModule(user.id, { ...moduleBody, revision: saved.revision, context: undefined, prices: { 'gpt-image-2.5-flare': 1, 'gpt-image-2.5-sunburst': 1 } }), /普通用户不能修改模块积分/);
  await changeStudioRatio(user.id, '10:6');
  await changeStudioRatio(user.id, '5:3');
  assert.deepEqual(await listStudioRatios(user.id), ['5:3']);
  assert.deepEqual(await listStudioRatios(stranger.id), []);
  await changeStudioRatio(stranger.id, '5:3', true);
  assert.deepEqual(await listStudioRatios(user.id), ['5:3']);
  await changeStudioRatio(user.id, '16:9');
  assert.deepEqual(await listStudioRatios(user.id), ['5:3'], 'built-in ratios do not become favorites');
  await assert.rejects(changeStudioRatio(user.id, '21:9', true), /不能删除/);
  await assert.rejects(changeStudioRatio(user.id, '5:1'));
  await changeStudioRatio(user.id, '5:3', true);
  assert.deepEqual(await listStudioRatios(user.id), []);
  assert.equal((await listStudioModules(user.id)).modules.find(item => item.id === moduleId)?.aspectRatio, '5:3', 'deleting a favorite does not change saved modules');
  await assert.rejects(saveStudioModule(stranger.id, { ...moduleBody, revision: saved.revision }, false, true), /无权/);
  await assert.rejects(saveStudioModule(user.id, moduleBody, false, true), /其他页面/);
  assert.equal((await listStudioModules(user.id)).modules.find(item => item.id === moduleId)?.context, 'Module context');
  assert.equal((await listStudioModules(user.id, undefined, true)).modules.find(item => item.id === moduleId)?.context, 'Module context');
  assert.equal((await listStudioModules(stranger.id)).modules.length, 1);
  await fs.mkdir(path.join(working, 'public/uploads'), { recursive: true });
  await fs.writeFile(path.join(working, 'public/uploads/reference.png'), png);
  const reference = await prisma.asset.create({ data: { owner_id: user.id, type: 'image', original_url: '/uploads/reference.png', file_name: 'reference.png', mime_type: 'image/png', file_size: png.length } });
  const referenceTwo = await prisma.asset.create({ data: { owner_id: user.id, type: 'image', original_url: '/uploads/reference.png', file_name: 'reference-two.png', mime_type: 'image/png', file_size: png.length } });
  const moduleBatch = await submitStudioBatch(user.id, { ...input, requestId: 'module-image-only-1234', moduleId, prompt: '', count: 1, aspectRatio: '5:3', referenceIds: [reference.id], revision: latest.revision });
  await assert.rejects(submitStudioBatch(user.id, { ...input, requestId: 'module-image-only-1234', moduleId, prompt: '', count: 1, aspectRatio: '4:3', referenceIds: [reference.id], revision: latest.revision }), /其他请求/);
  const moduleTaskBeforeRun = await prisma.imageStudioTask.findFirstOrThrow({ where: { batch_id: moduleBatch } });
  assert.equal(moduleTaskBeforeRun.context, 'New context\n\n---\n模块上下文：\nModule context');
  const moduleSnapshot = JSON.parse(moduleTaskBeforeRun.snapshot_json || '{}');
  assert.equal(moduleSnapshot.model, 'gpt-image-2.5-sunburst');
  assert.equal(moduleSnapshot.unitCredits, 9);
  assert.equal(moduleSnapshot.referenceImages[0].id, reference.id);
  await processStudioTask(async args => {
    assert.equal(args.size, '1360x816');
    assert.equal(args.images.length, 1); assert.ok(args.prompt.endsWith('Module context')); assert.ok(!args.prompt.includes('本次画面要求'));
    return { images: [png.toString('base64')], usage: null };
  });
  assert.equal((await listStudioTasks(user.id, undefined, moduleId)).tasks.length, 1);
  assert.equal((await listStudioTasks(user.id, undefined, defaultStudioModuleId(user.id))).tasks.length, 3);
  assert.equal((await listStudioTasks(stranger.id, undefined, moduleId)).tasks.length, 0);
  assert.equal((await listStudioTasks(user.id, undefined, moduleId)).tasks[0].status, 'succeeded');
  assert.equal((await listStudioTasks(user.id, undefined, moduleId)).tasks[0].snapshot.referenceImages[0].id, reference.id);
  const historicalTask = await prisma.imageStudioTask.findFirstOrThrow({ where: { batch_id: moduleBatch } });
  const changedModule = await saveStudioModule(user.id, { ...moduleBody, revision: saved.revision, context: 'Current module context', reproduceFromTaskId: historicalTask.id }, false, true);
  assert.equal(changedModule.reproduceFromTaskId, historicalTask.id);
  assert.equal((await listStudioModules(user.id, undefined, true)).modules.find(item => item.id === moduleId)?.reproduceFromTaskId, historicalTask.id);
  const reproducedBatch = await submitStudioBatch(user.id, {
    ...input, requestId: 'reproduce-history-1234', moduleId, moduleRevision: changedModule.revision,
    prompt: 'changed prompt with a new reference', count: 1, aspectRatio: '5:3', referenceIds: [referenceTwo.id], revision: latest.revision,
  });
  const reproducedTask = await prisma.imageStudioTask.findFirstOrThrow({ where: { batch_id: reproducedBatch } });
  assert.equal(reproducedTask.context, 'New context\n\n---\n模块上下文：\nModule context', 'reproduction must use the source snapshot context');
  assert.equal(JSON.parse(reproducedTask.snapshot_json || '{}').moduleContext, 'Module context');
  assert.deepEqual(JSON.parse(reproducedTask.reference_ids), [referenceTwo.id], 'reproduction must use the references currently selected by the user');
  const clearedModule = await saveStudioModule(user.id, { ...moduleBody, revision: changedModule.revision, context: 'Current module context', reproduceFromTaskId: null }, false, true);
  assert.equal(clearedModule.reproduceFromTaskId, null);
  await processStudioTask(async () => ({ images: [png.toString('base64')], usage: null }));
  await assert.rejects(submitStudioBatch(stranger.id, { ...input, requestId: 'forbidden-module-1234', revision: latest.revision, moduleId }), /无权/);
  const result = (await listStudioTasks(user.id, undefined, moduleId)).tasks.find(task => task.batchId === moduleBatch)!;
  assert.equal(result.aspectRatio, '5:3'); assert.equal(result.outputSize, '1360x816');
  const beforeDelete = await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } });
  const ledgerCount = await prisma.creditLedger.count();
  await assert.rejects(deleteStudioResult(stranger.id, result.id), /无权/);
  const failed = await prisma.imageStudioTask.findFirstOrThrow({ where: { status: 'uncertain' } });
  await assert.rejects(deleteStudioResult(user.id, failed.id), /只能删除/);
  await deleteStudioResult(user.id, result.id); await deleteStudioResult(user.id, result.id);
  assert.equal((await listStudioTasks(user.id, undefined, moduleId)).tasks.length, 1);
  assert.equal((await listStudioTasks(user.id, undefined, defaultStudioModuleId(user.id))).tasks.length, 3);
  assert.ok((await prisma.imageStudioTask.findUniqueOrThrow({ where: { id: result.id } })).deleted_at);
  assert.equal((await prisma.asset.findUniqueOrThrow({ where: { id: result.asset!.id } })).status, 'active');
  assert.equal(await prisma.creditLedger.count(), ledgerCount);
  assert.deepEqual(await prisma.creditAccount.findUniqueOrThrow({ where: { user_id: user.id } }), beforeDelete);
  for (let i = 1; i <= 32; i++) await changeStudioRatio(user.id, `${1000 + i}:1000`);
  await assert.rejects(changeStudioRatio(user.id, '1033:1000'), /最多保存/);
  assert.equal((await listStudioRatios(user.id)).length, 32);
  console.log('PASS: immutable context, idempotent submit/settlement, per-image charging/refund, owner isolation, stale-setting conflict, expired lease recovery, saved PNG. No network generation.');
  await prisma.$disconnect();
}
void main().catch(async error => { console.error(error); await prisma.$disconnect(); process.exitCode = 1; });
