import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import os from 'node:os';

// Isolated fixtures only: never attach to a user's browser or contact production.
const root = process.cwd(), localRequire = createRequire(path.join(root, 'package.json'));
const entry = `
import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AppSessionProvider,useAppSession} from './src/lib/context/AppSessionContext';
import {ZoomableImagePreview} from './src/components/ZoomableImagePreview';
import {ContextClipboardActions} from './src/components/ContextClipboardActions';
import {RatioPicker} from './src/app/image-studio/ratio-picker';
import {useStudioBatch} from './src/app/image-studio/use-studio-batch';
import {BatchResults} from './src/app/image-studio/batch-results';
import CutoutPage from './src/app/cutout/page';
import {scrollToWorkbenchHeader} from './src/lib/navigation/scroll-to-workbench-header';
import studioStyles from './src/app/image-studio/studio.module.css';
import './src/app/globals.css';
const images=['a','b','c','bad','slow'].map(id=>({src:'/fixture/'+id+'.png',alt:'生成结果 '+id,pickerKey:'asset:'+id,contentKey:'asset:'+id}));
function Preview(){const [open,setOpen]=useState(true),[index,setIndex]=useState(0);return <><button onClick={()=>setOpen(true)}>打开大图</button>{open&&<ZoomableImagePreview src={images[index].src} alt='生成结果' previewKey='fixture-root' comparison={location.search==='?seed=1'?images[1]:undefined} comparisonCandidates={images} hasNavigation onPrevious={()=>setIndex(value=>(value+2)%3)} onNext={()=>setIndex(value=>(value+1)%3)} onClose={()=>setOpen(false)}/>}</>}
function Paste(){const [value,setValue]=useState('旧正文'),[disabled,setDisabled]=useState(false),[visible,setVisible]=useState(true),[changes,setChanges]=useState(0);const ref=useRef(null);return <main><button onClick={()=>setDisabled(value=>!value)}>切换权限</button><button onClick={()=>setVisible(value=>!value)}>切换挂载</button><output data-testid='changes'>{changes}</output>{visible&&<><ContextClipboardActions value={value} textareaRef={ref} maxLength={12} disabled={disabled} onPaste={text=>{setValue(text);setChanges(value=>value+1)}}/><textarea aria-label='正文' ref={ref} value={value} onChange={event=>setValue(event.target.value)}/></>}</main>}
function Batch(){const [draft,setDraft]=useState('fixture'),[owner,setOwner]=useState('fixture-admin');const batch=useStudioBatch({userId:owner,moduleId:'fixture-module',unitCredits:8,draftSignature:draft});return <main><button onClick={()=>batch.setMode('batch')}>批量模式</button><button onClick={()=>setDraft(value=>value+'x')}>修改正文</button><button onClick={()=>setOwner('other-fixture')}>切换账号</button>{batch.mode==='batch'&&batch.controls}<button aria-label='准备生成' disabled={!!batch.blocker||batch.busy} onClick={()=>void batch.submit({model:'gemini-2.5-flash-image',quality:'standard',resolution:'1K',aspectRatio:'1:1',revision:1,prompt:draft,moduleId:'fixture-module'})}>准备生成</button><output data-testid='batch-state'>{JSON.stringify({id:batch.id,pending:batch.pending,blocker:batch.blocker})}</output></main>}
function Ratio(){const[value,setValue]=useState('1:1');return <main style={{padding:24,width:280}}><RatioPicker value={value} onChange={setValue} model='gemini-2.5-flash-image' resolution='1K' custom={[]} busy={false} disabled={false} error='' onRetry={()=>{}} onCustom={async()=>true} onEditing={()=>{}} fourToOneSupported={true}/></main>}
function Navigation(){const target=useRef(null),layout=useRef(null);return <><div className='composer-topbar' style={{position:'fixed',top:0,left:0,width:'100%',height:70,zIndex:2,background:'#bbb'}}>示例导航</div><main ref={layout}><button style={{position:'fixed',top:4,right:4,zIndex:3}} onClick={()=>scrollToWorkbenchHeader(target.current,layout.current,'auto',()=>{window.navSettled=true})}>定位模块</button><div id='preceding' style={{height:1400}}/><header ref={target} data-testid='module-header' style={{height:60}}>当前模块标题</header><div style={{height:1400}}/></main></>}
function StickyNavigation(){const target=useRef(null),layout=useRef(null);return <><div className='composer-topbar' style={{position:'fixed',top:0,left:0,width:'100%',height:76.64,zIndex:20,background:'#151a1d'}}>合成工作台</div><main ref={layout} className={studioStyles.page+' '+studioStyles.templateWorkbench} style={{'--composer-topbar-height':'76.64px'}}><nav className={studioStyles.mobileModuleNav} aria-label='图片模块导航'><div className={studioStyles.mobileMajorLinks}>合成模板导航</div><label><span>当前模块</span><select aria-label='示例模块' onChange={()=>{window.navSettled=false;scrollToWorkbenchHeader(target.current,layout.current,'auto',()=>{window.navSettled=true})}}><option value='first'>第一模块</option><option value='target'>目标模块</option></select></label><button onClick={()=>{window.navSettled=false;scrollToWorkbenchHeader(target.current,layout.current,'auto',()=>{window.navSettled=true})}}>定位当前模块</button></nav><div id='preceding' style={{height:6800,background:'#182126'}}>合成前序模块</div><header ref={target} data-testid='module-header' style={{height:90,background:'#253f38'}}>当前模块标题</header><div style={{height:2700}}/></main></>}
function Boot(){const{refreshUser}=useAppSession();useEffect(()=>{history.replaceState({},'');void refreshUser()},[refreshUser]);const route=location.pathname;return route==='/paste'?<Paste/>:route==='/batch'?<Batch/>:route==='/ratio'?<Ratio/>:route==='/navigation'?<Navigation/>:route==='/navigation-sticky'?<StickyNavigation/>:route==='/cutout'?<CutoutPage/>:route==='/results'?<BatchResults userId='fixture-admin' id={'a'.repeat(64)} deliveryOnly={location.search==='?delivery=1'}/>:<Preview/>}
createRoot(document.getElementById('root')).render(<AppSessionProvider><Boot/></AppSessionProvider>);
`;

async function main() {
  const failures: string[] = [], passed: string[] = [], errors: string[] = [], external: string[] = [];
  const requests: Array<{ path: string; method: string; key?: string; body?: any }> = [];
  let browser: any, server: http.Server | undefined, fixtureDirectory: string | undefined;
  const run = async (label: string, action: () => Promise<void>) => { if (process.env.FOLLOWUPS_CASE && !label.startsWith(process.env.FOLLOWUPS_CASE)) return; try { await action(); passed.push(label); } catch (error) { failures.push(`${label}: ${error instanceof Error ? error.message : error}`); } };
  try {
    const esbuild = localRequire('esbuild'), sharp = localRequire('sharp');
    const built = await esbuild.build({ absWorkingDir: root, stdin: { contents: entry, loader: 'tsx', resolveDir: root }, bundle: true, write: false, outfile: '/tmp/sd2-followups-fixture.js', platform: 'browser', format: 'iife', target: ['chrome120'], jsx: 'automatic', define: {'process.env.NODE_ENV':'"production"'}, loader: {'.css':'local-css'}, logLevel:'silent', plugins:[{name:'fixture-link',setup(build:any){build.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:"import React from 'react';export default function Link({href,prefetch,replace,scroll,...props}){return <a href={href} {...props}/>}",loader:'jsx',resolveDir:root}));}}] });
    const js = built.outputFiles.find((file:any)=>file.path.endsWith('.js'))!.text, css = built.outputFiles.find((file:any)=>file.path.endsWith('.css'))!.text;
    const images = new Map<string,Buffer>();
    for (const [id,color,width,height] of [['a','#bd4047',480,320],['b','#2c896f',320,480],['c','#3e72a9',800,300],['slow','#996e20',600,400]] as const) images.set(id, await sharp({create:{width,height,channels:4,background:color}}).png().toBuffer());
    fixtureDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'sd2-batch-fixture-'));
    for(const id of ['a','b'])fs.writeFileSync(path.join(fixtureDirectory,`${id}.png`),images.get(id)!);
    server = http.createServer((req,res)=>{const url=new URL(req.url!,'http://localhost');if(url.pathname==='/bundle.js'||url.pathname==='/bundle.css'){res.setHeader('content-type',url.pathname.endsWith('.js')?'text/javascript':'text/css');res.end(url.pathname.endsWith('.js')?js:css)}else if(url.pathname.startsWith('/fixture/')){const id=path.basename(url.pathname,'.png'),image=images.get(id);if(!image){res.writeHead(404);res.end();return}const send=()=>{res.setHeader('content-type','image/png');res.setHeader('content-length',image.length);res.end(image)};if(id==='slow')setTimeout(send,750);else send()}else{res.setHeader('content-type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/bundle.css"><div id="root"></div><script src="/bundle.js"></script>')}});
    await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));
    const origin=`http://127.0.0.1:${(server.address() as any).port}`;
    const {chromium}=localRequire(process.env.PLAYWRIGHT_MODULE || '/Users/gouki-youdoo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
    browser=await chromium.launch({headless:true,channel:'chrome'});
    const context=await browser.newContext({viewport:{width:1365,height:900}});
    // tsx preserves nested function names when serializing Playwright callbacks.
    await context.addInitScript('globalThis.__name = (fn) => fn');
    let cutReady=false, invalidJob=true, batchInvalid=true, settingsPrice=8;
    const pickerItems=['a','b','c','bad','slow'].map(id=>({key:`asset:${id}`,identity:`asset:${id}`,id,type:'image',originalUrl:`/fixture/${id}.png`,thumbnailUrl:`/fixture/${id}.png`,fileName:`${id}.png`,width:480,height:320,createdAt:'2026-10-06T00:00:00Z',source:'uploaded'}));
    await context.route('**/*',async(route:any)=>{const req=route.request(),url=new URL(req.url());if(url.origin!==origin&&!['blob:','data:'].includes(url.protocol)){external.push(url.origin);return route.abort()}if(!url.pathname.startsWith('/api/'))return route.continue();const body=req.headers()['content-type']?.includes('application/json')?req.postDataJSON():undefined;requests.push({path:url.pathname,method:req.method(),key:req.headers()['idempotency-key'],body});const reply=(data:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
      if(url.pathname==='/api/auth/me')return reply({user:{id:'fixture-admin',name:'示例',role:'admin',account_type:'internal'}});
      if(url.pathname==='/api/me/credits')return reply({available:1000,frozen_credits:0,monthly_used:0});
      if(url.pathname==='/api/image-studio/settings')return reply({revision:1,prices:{'gemini-2.5-flash-image':settingsPrice}});
      if(url.pathname==='/api/assets/picker')return reply({items:pickerItems.filter(item=>!url.searchParams.get('keys')||item.key===url.searchParams.get('keys')),albums:[],total:5,page:1,hasMore:false});
      if(url.pathname==='/api/content-reactions/state')return reply({states:Object.fromEntries((body?.keys||[]).map((key:string)=>[key,{key,liked:false,favorited:false,likeCount:0,version:0,available:true}]))});
      if(url.pathname==='/api/image-shares')return reply({canShare:false,shared:false});
      if(url.pathname.endsWith('/capabilities'))return reply({models:[{id:'birefnet',available:true},{id:'facebook/sam-vit-base',available:true}],worker:{online:true},dispatch:{available:true},integration:{configured:cutReady,authorized:cutReady,ready:cutReady,message:''},limits:{max_upload_mb:15}});
      if(url.pathname.endsWith('/jobs/history'))return cutReady?reply({items:[],total:0}):reply({success:false,error:'UNCONFIGURED',message:'请稍后再试',submission_made:false},503);
      if(url.pathname.endsWith('/assets'))return reply({asset_id:'fixture-asset',width:480,height:320,size:images.get('a')!.length},201);
      if(url.pathname.endsWith('/jobs')&&req.method()==='POST')return reply(invalidJob?{success:true}:{job_id:'fixture-job',kind:body.kind,status:'queued',created_at:1,updated_at:1,parameters:body.parameters},202);
      if(url.pathname==='/api/image-studio/batches')return reply(batchInvalid?{success:true}:{batch:{id:'a'.repeat(64),requestId:'fixture-original-request',moduleId:'fixture-module',moduleName:'示例模板',model:'gemini-2.5-flash-image',state:'complete',note:'',total:2,generated:2,failed:0,uncertain:0,active:0,pending:0,prepared:2,budget:16,committedCredits:16,unitCredits:8,createdAt:'2026-10-06T00:00:00Z',items:[1,2].map((ordinal)=>({ordinal,sourceName:'示例',taskId:`fixture-task-${ordinal}`,status:'succeeded',image:{id:`fixture-${ordinal}`,url:'/fixture/a.png',thumbnail:'/fixture/a.png',fileSize:images.get('a')!.length}}))}});
      if(url.pathname==='/api/image-studio/download')return reply({error:'模拟打包失败'},503);
      return reply({success:true});
    });
    const page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',(error:Error)=>errors.push(error.message));
    const go=async(route:string)=>{await page.goto(origin+route);await page.waitForTimeout(120)};
    const view=(side:string)=>page.locator(`[data-image-preview-pane="${side}"] img[data-image-preview-image]`).filter({visible:true});
    const waitImage=async(side:string)=>page.waitForFunction((side:string)=>{const pane=document.querySelector(`[data-image-preview-pane="${side}"]`);return Array.from(pane?.querySelectorAll<HTMLImageElement>('img[data-image-preview-image]')||[]).some(img=>img.complete&&img.naturalWidth&&getComputedStyle(img).opacity==='1')},side);
    const wheel=async(side:string,delta:number,count=1)=>{await page.locator(`[data-image-preview-pane="${side}"]`).evaluate((pane:HTMLElement,{delta,count}:any)=>{const r=pane.getBoundingClientRect();for(let i=0;i<count;i++)pane.dispatchEvent(new WheelEvent('wheel',{bubbles:true,cancelable:true,clientX:r.left+r.width*.35,clientY:r.top+r.height*.4,deltaY:delta}))},{delta,count});await page.waitForTimeout(50)};
    const transform=async(side:string)=>view(side).last().getAttribute('style');
    const screenshot=async(name:string)=>{if(process.env.FOLLOWUPS_EVIDENCE_DIR)await page.screenshot({path:path.join(process.env.FOLLOWUPS_EVIDENCE_DIR,name+'.png')});};
    if(process.env.FOLLOWUPS_EVIDENCE_DIR)fs.mkdirSync(process.env.FOLLOWUPS_EVIDENCE_DIR,{recursive:true});
    await run('CMP seeded reference with mode off preloads before success; failure and cancellation keep single layout',async()=>{
      await go('/preview?seed=1');await waitImage('current');assert.equal(await page.locator('[data-image-preview-pane]').count(),1);
      const original=await transform('current');await page.getByRole('button',{name:'选择或更换对比图'}).click();
      await page.getByRole('button',{name:'生成结果 bad',exact:true}).click();await page.getByText('图片未能加载，原图保留，请重新选择',{exact:true}).first().waitFor();
      assert.equal(await page.locator('[data-image-preview-pane]').count(),1);assert.equal(await page.getByRole('button',{name:'开启对比'}).getAttribute('aria-pressed'),'false');assert.equal(await transform('current'),original);
      await page.getByRole('button',{name:'生成结果 slow',exact:true}).click({noWaitAfter:true});await page.locator('[data-image-preview-preload]').waitFor({state:'attached'});
      assert.equal(await page.locator('[data-image-preview-pane]').count(),1);await page.keyboard.press('Escape');await page.waitForTimeout(900);
      assert.equal(await page.locator('[data-image-preview-pane]').count(),1);assert.equal(await page.locator('[data-image-preview-preload]').count(),0);
      await page.getByRole('button',{name:'开启对比'}).click();await waitImage('comparison');assert.equal(await view('comparison').last().evaluate((img:HTMLImageElement)=>img.naturalWidth),320);
      await page.getByRole('button',{name:'退出对比'}).click();await page.getByRole('button',{name:'选择或更换对比图'}).click();await page.getByRole('button',{name:'生成结果 slow',exact:true}).click({noWaitAfter:true});
      await page.locator('[data-image-preview-preload]').waitFor({state:'attached'});assert.equal(await page.locator('[data-image-preview-pane]').count(),1);await waitImage('comparison');await page.getByRole('dialog',{name:'选择对比图'}).waitFor({state:'hidden'});
      assert.equal(await view('comparison').last().evaluate((img:HTMLImageElement)=>img.naturalWidth),600);
      await page.getByRole('button',{name:'退出对比'}).click();await page.getByRole('button',{name:'选择或更换对比图'}).click();await page.getByRole('button',{name:'生成结果 b',exact:true}).click();await waitImage('comparison');
      assert.equal(await view('comparison').last().evaluate((img:HTMLImageElement)=>img.naturalWidth),320);await screenshot('cmp-seeded-reference-desktop');await page.getByRole('button',{name:'关闭大图'}).click();
    });
    await run('CMP independent position, <1 drag, cursor wheel, linked no jump, navigation preserves comparison',async()=>{await go('/preview');await waitImage('current');await page.getByRole('button',{name:'选择或更换对比图'}).click();await page.getByRole('button',{name:'生成结果 b',exact:true}).click();await waitImage('comparison');const before=await transform('comparison');await wheel('current',-100);assert.equal(await transform('comparison'),before);await wheel('current',100,12);const pane=await page.locator('[data-image-preview-pane="current"]').boundingBox();const t=await transform('current');await page.mouse.move(pane.x+pane.width*.5,pane.y+pane.height*.5);await page.mouse.down();await page.mouse.move(pane.x+pane.width*.5+42,pane.y+pane.height*.5+24);await page.mouse.up();assert.notEqual(await transform('current'),t);const positions=[await transform('current'),await transform('comparison')];await page.getByRole('checkbox',{name:'联动'}).check();assert.deepEqual([await transform('current'),await transform('comparison')],positions);await wheel('current',-100);assert.notEqual(await transform('comparison'),positions[1]);await page.getByRole('checkbox',{name:'联动'}).uncheck();const comp=await transform('comparison');await page.getByRole('button',{name:'当前图下一张'}).click();await waitImage('current');assert.equal(await transform('comparison'),comp);});
    await run('CMP failed selection keeps image; late requests do not override; internal blank and topmost Escape',async()=>{await page.getByRole('button',{name:'选择或更换对比图'}).click();await page.getByRole('button',{name:'生成结果 bad',exact:true}).click();await page.getByText('图片未能加载，原图保留，请重新选择',{exact:true}).first().waitFor();await waitImage('comparison');await page.getByRole('button',{name:'生成结果 slow',exact:true}).click({noWaitAfter:true});await page.getByRole('button',{name:'生成结果 c',exact:true}).click();await waitImage('comparison');await page.waitForTimeout(900);const dimensions=await view('comparison').last().evaluate((image:HTMLImageElement)=>image.naturalWidth);assert.equal(dimensions,800);await page.locator('[data-image-preview-pane="comparison"]').click({position:{x:5,y:5}});assert.equal(await page.locator('[data-media-preview]').count(),1);await page.getByRole('button',{name:'更换当前图'}).click();await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog',{name:'选择当前图'}).count(),0);assert.equal(await page.locator('[data-media-preview]').count(),1);});
    await run('CMP swap/layout retain view; selected reset vs both reset; phone Back closes only top layer',async()=>{await page.getByRole('combobox',{name:'对比更多操作'}).selectOption('swap');await page.getByRole('button',{name:'切换上下对比'}).click();await page.getByRole('button',{name:/还原(当前|对比)图/}).click();await page.getByRole('combobox',{name:'对比更多操作'}).selectOption('reset');await page.getByRole('button',{name:'更换当前图'}).click();await page.goBack();await page.getByRole('dialog',{name:'选择当前图'}).waitFor({state:'hidden'});assert.equal(await page.locator('[data-media-preview]').count(),1);await page.goBack();await page.locator('[data-media-preview]').waitFor({state:'hidden'});});
    await run('CMP mobile controls and temporary local selection without upload',async()=>{await page.setViewportSize({width:390,height:844});await go('/preview');await waitImage('current');const close=await page.getByRole('button',{name:'关闭大图'}).boundingBox();assert.ok(close&&close.x>=0&&close.x+close.width<=390);await page.getByRole('button',{name:'选择或更换对比图'}).click();const writes=requests.length;await page.getByRole('dialog',{name:'选择对比图'}).locator('input[type=file]').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:images.get('b')!});await waitImage('comparison');assert.equal(requests.slice(writes).filter(req=>req.method!=='GET'&&req.path!=='/api/content-reactions/state').length,0);await page.getByRole('button',{name:'关闭大图'}).click();});
    await page.setViewportSize({width:1365,height:900});
    await run('CMP same-image independence, cursor anchor, single-frame pinch and cross-frame isolation',async()=>{
      await go('/preview');await waitImage('current');await page.getByRole('button',{name:'选择或更换对比图'}).click();await page.getByRole('button',{name:'生成结果 a',exact:true}).click();await waitImage('comparison');await page.getByRole('checkbox',{name:'联动'}).uncheck();
      const other=await transform('comparison'),pane=await page.locator('[data-image-preview-pane="current"]').boundingBox();
      const anchor={x:pane.x+pane.width*.35,y:pane.y+pane.height*.4},before=await view('current').last().boundingBox();await wheel('current',-100);const after=await view('current').last().boundingBox();
      assert.equal(await transform('comparison'),other);assert.ok(Math.abs((anchor.x-before.x)/before.width-(anchor.x-after.x)/after.width)<.002);assert.ok(Math.abs((anchor.y-before.y)/before.height-(anchor.y-after.y)/after.height)<.002);
      const cdp=await context.newCDPSession(page),touch=async(type:string,points:any[])=>{await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});await page.waitForTimeout(40)};
      const center={x:pane.x+pane.width*.5,y:pane.y+pane.height*.5},point=(id:number,x:number,y:number)=>({id,x,y,radiusX:2,radiusY:2,force:1});
      const oldWidth=(await view('current').last().boundingBox()).width;
      await touch('touchStart',[point(1,center.x-30,center.y),point(2,center.x+30,center.y)]);await touch('touchMove',[point(1,center.x-60,center.y),point(2,center.x+60,center.y)]);await touch('touchEnd',[]);
      assert.ok((await view('current').last().boundingBox()).width>oldWidth*1.5);assert.equal(await transform('comparison'),other);
      const right=await page.locator('[data-image-preview-pane="comparison"]').boundingBox(),widths=[(await view('current').last().boundingBox()).width,(await view('comparison').last().boundingBox()).width];
      await touch('touchStart',[point(1,center.x,center.y),point(2,right.x+right.width*.5,right.y+right.height*.5)]);await touch('touchMove',[point(1,center.x+20,center.y),point(2,right.x+right.width*.5-20,right.y+right.height*.5)]);await touch('touchEnd',[]);
      const nextWidths=[(await view('current').last().boundingBox()).width,(await view('comparison').last().boundingBox()).width];assert.ok(nextWidths.every((value,index)=>Math.abs(value-widths[index])<1));await cdp.detach();await page.getByRole('button',{name:'关闭大图'}).click();
    });
    await run('PASTE full replacement, caret end, same value clean, whole length rejection, empty and denied clipboard',async()=>{await go('/paste');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=> '新正文'}}));await page.getByRole('button',{name:'粘贴并替换上下文全文'}).click();assert.equal(await page.getByRole('textbox',{name:'正文'}).inputValue(),'新正文');await page.waitForFunction(()=>{const input=document.querySelector('textarea')!;return input.selectionStart===3&&input.selectionEnd===3});assert.equal(await page.getByTestId('changes').textContent(),'1');await page.getByRole('button',{name:'粘贴并替换上下文全文'}).click();assert.equal(await page.getByTestId('changes').textContent(),'1');for(const text of ['超过最大长度的文字超过最大长度','']){await page.evaluate((text:string)=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>text}}),text);await page.getByRole('button',{name:'粘贴并替换上下文全文'}).click();assert.equal(await page.getByRole('textbox',{name:'正文'}).inputValue(),'新正文')}await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>{throw new Error('denied')}}}));await page.getByRole('button',{name:'粘贴并替换上下文全文'}).click();await page.getByText('无法读取剪贴板，请在输入框内粘贴').waitFor();});
    await run('PASTE asynchronous changes, lost permission and unmount never overwrite',async()=>{for(const action of ['edit','permission','unmount']){await go('/paste');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:()=>new Promise(resolve=>{(window as any).resolvePaste=resolve})}}));await page.getByRole('button',{name:'粘贴并替换上下文全文'}).click();if(action==='edit')await page.getByRole('textbox',{name:'正文'}).fill('期间修改');else await page.getByRole('button',{name:action==='permission'?'切换权限':'切换挂载'}).click();await page.evaluate(()=>(window as any).resolvePaste('不应覆盖'));await page.waitForTimeout(60);assert.equal(await page.getByTestId('changes').textContent(),'0');}});
    await run('BUX local folder preparation and cancel cause zero upload/task; actual number-price confirmation',async()=>{await go('/batch');await page.getByRole('button',{name:'批量模式'}).click();const before=requests.length;await page.locator('input[webkitdirectory]').setInputFiles(fixtureDirectory!);await page.getByText(/2张素材/).waitFor();assert.equal(requests.slice(before).length,0);await page.getByRole('button',{name:'准备生成'}).click();const confirm=page.getByRole('dialog',{name:'确认生成'});await confirm.waitFor();await confirm.getByText(/生成2张/).waitFor();await confirm.getByText(/预计16点/).waitFor();await confirm.getByRole('button',{name:'取消',exact:true}).click();assert.equal(requests.slice(before).filter(req=>req.method!=='GET').length,0);});
    await run('BUX changed quote refuses before upload, old text mode remains, unknown receipt preserves original request',async()=>{await page.getByRole('button',{name:'其他设置'}).click();await page.getByRole('combobox',{name:'批量来源'}).selectOption('current');settingsPrice=9;const before=requests.length;await page.getByRole('button',{name:'准备生成'}).click();await page.getByText('素材、模型或报价已变化，请重新读取设置后确认；尚未生成').waitFor();assert.equal(requests.slice(before).filter(req=>req.method!=='GET').length,0);settingsPrice=8;await page.getByRole('button',{name:'准备生成'}).click();await page.getByRole('dialog',{name:'确认生成'}).getByRole('button',{name:'确认生成 · 64点'}).click();await page.getByText('批次回执尚未确认，请查询原提交，不会重新生成').waitFor();const pending=JSON.parse(await page.getByTestId('batch-state').textContent());assert.ok(pending.pending);const posts=requests.filter(req=>req.path==='/api/image-studio/batches'&&req.method==='POST');assert.equal(posts.length,1);await page.getByRole('button',{name:'查询原批次'}).click();assert.equal(requests.filter(req=>req.path==='/api/image-studio/batches'&&req.method==='POST').length,1);});
    await run('BUX download failure never regenerates; result previews and batch asset link available',async()=>{batchInvalid=false;await go('/results');await page.getByRole('button',{name:'下载第 1 包 · 2 张'}).waitFor();const before=requests.length;await page.getByRole('button',{name:'下载第 1 包 · 2 张'}).click();await page.getByText(/模拟打包失败/).waitFor();assert.equal(requests.slice(before).filter(req=>req.method!=='GET').length,0);assert.equal(await page.getByRole('button',{name:/预览第 .* 张结果/}).count(),2);await go('/results?delivery=1');assert.equal(await page.getByRole('link',{name:'本批资产'}).getAttribute('href'),'/assets?imageBatchId='+ 'a'.repeat(64));});
    await run('B6 ratio information quiet by default and visible on focus/explicit info control',async()=>{await go('/ratio');await page.mouse.move(1000,700);assert.equal(await page.getByRole('tooltip').isVisible(),false);await page.getByRole('button',{name:'比例与请求尺寸'}).click();assert.equal(await page.getByRole('tooltip').isVisible(),true);await page.keyboard.press('Escape');await page.mouse.click(1100,700);assert.equal(await page.getByRole('tooltip').isVisible(),false);await page.getByRole('button',{name:'图片比例 1:1'}).focus();assert.equal(await page.getByRole('tooltip').isVisible(),true);});
    await run('SIDE actual header tracks preceding layout shift and topbar; scroll settled',async()=>{await go('/navigation');await page.getByRole('button',{name:'定位模块'}).click();await page.waitForTimeout(200);await page.locator('#preceding').evaluate((element:HTMLElement)=>element.style.height='1800px');await page.waitForFunction(()=>(window as any).navSettled);const box=await page.getByTestId('module-header').boundingBox();const bar=await page.locator('.composer-topbar').boundingBox();assert.ok(Math.abs(box.y-(bar.y+bar.height))<1,JSON.stringify({header:box,topbar:bar,scroll:await page.evaluate(()=>window.scrollY)}));});
    await run('SIDE real document overflow and studio sticky navigation at 1068 and 390; no phantom occlusion',async()=>{
      for(const width of [1068,390]){await page.setViewportSize({width,height:873});await go('/navigation-sticky');
        await page.getByRole('combobox',{name:'示例模块'}).selectOption('target');await page.waitForFunction(()=>(window as any).navSettled);
        const rects=await page.evaluate(()=>{const nav=document.querySelector('[aria-label="图片模块导航"]')!.getBoundingClientRect(),bar=document.querySelector('.composer-topbar')!.getBoundingClientRect(),header=document.querySelector('[data-testid="module-header"]')!.getBoundingClientRect();return {navTop:nav.top,navBottom:nav.bottom,barBottom:bar.bottom,headerTop:header.top,bodyOverflowX:getComputedStyle(document.body).overflowX,bodyOverflowY:getComputedStyle(document.body).overflowY,htmlOverflowX:getComputedStyle(document.documentElement).overflowX,scrollY,bodyHeight:document.body.offsetHeight,htmlHeight:document.documentElement.clientHeight,overflow:document.documentElement.scrollWidth>innerWidth};});
        assert.equal(rects.bodyOverflowX,'clip');assert.equal(rects.bodyOverflowY,'visible');assert.equal(rects.htmlOverflowX,'hidden');assert.ok(rects.bodyHeight>9000&&rects.scrollY>6000);assert.ok(Math.abs(rects.navTop-rects.barBottom)<1,JSON.stringify(rects));assert.ok(Math.abs(rects.headerTop-rects.navBottom)<1,JSON.stringify(rects));assert.equal(rects.overflow,false);await screenshot('side-sticky-'+width);
        await page.locator('[aria-label="图片模块导航"]').evaluate((nav:HTMLElement)=>nav.style.position='static');await page.getByRole('button',{name:'定位当前模块'}).evaluate((button:HTMLButtonElement)=>button.click());await page.waitForFunction(()=>(window as any).navSettled);
        assert.ok(Math.abs((await page.getByTestId('module-header').boundingBox()).y-rects.barBottom)<1,'offscreen navigation must not reserve phantom height');
      }await page.setViewportSize({width:1365,height:900});
    });
    await run('CUT account-specific unavailable/history message, no task; ResourceLibraryPicker success and failed selection preserve source',async()=>{await go('/cutout');await page.getByText('当前账户尚未绑定抠图授权，暂不能提交任务。',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'开始普通抠图'}).isDisabled(),true);assert.equal(await page.getByText(/当前账户尚未绑定抠图授权.*历史记录/).count(),1);await page.getByRole('button',{name:'选择图片',exact:true}).click();const picker=page.getByRole('dialog',{name:'选择抠图原图'});await picker.waitFor();await picker.getByRole('button',{name:'选择a.png',exact:true}).click();await picker.getByRole('button',{name:/使用所选图片/}).click();await page.getByRole('img',{name:'当前处理图片'}).waitFor();const original=await page.getByRole('img',{name:'当前处理图片'}).getAttribute('src');await page.getByRole('button',{name:'选择图片',exact:true}).click();await picker.getByRole('button',{name:'选择bad.png',exact:true}).click();await picker.getByRole('button',{name:/使用所选图片/}).click();await picker.getByRole('alert').filter({hasText:'所选原图无法读取，原图和旧结果保留'}).waitFor();assert.equal(await page.getByRole('img',{name:'当前处理图片'}).getAttribute('src'),original);await page.keyboard.press('Escape');assert.equal(requests.filter(req=>req.path.endsWith('/jobs')&&req.method==='POST').length,0);});
    await run('CUT namespace SAM respects available; invalid acceptance retains parameters/key on retry',async()=>{cutReady=true;await page.getByRole('button',{name:'重新检查服务'}).click();await page.getByRole('tab',{name:'角色拆切',exact:true}).click();assert.equal(await page.getByRole('button',{name:'SAM 手动框选',exact:true}).isEnabled(),true);await page.getByRole('tab',{name:'普通抠图',exact:true}).click();await page.getByRole('button',{name:'开始普通抠图'}).click();await page.getByRole('button',{name:'重试确认提交'}).waitFor();await page.getByRole('button',{name:'重试确认提交'}).click();await page.waitForTimeout(80);const posts=requests.filter(req=>req.path.endsWith('/jobs')&&req.method==='POST');assert.equal(posts.length,2);assert.equal(posts[0].key,posts[1].key);assert.deepEqual(posts[0].body,posts[1].body);assert.equal(await page.getByText('任务已受理',{exact:true}).count(),0);});
    assert.equal(external.length,0,'no production or external network');
    if(errors.length)failures.push(...errors.map(error=>`page runtime: ${error}`));
    const evidence={kind:'isolated fixed regression; not authenticated production evidence',passed,failures,externalRequests:external,productionUploads:0,productionTasks:0,fees:0};
    if(process.env.FOLLOWUPS_EVIDENCE_DIR){fs.mkdirSync(process.env.FOLLOWUPS_EVIDENCE_DIR,{recursive:true});fs.writeFileSync(path.join(process.env.FOLLOWUPS_EVIDENCE_DIR,'isolated-ui.json'),JSON.stringify(evidence,null,2));}
    console.log(JSON.stringify(evidence,null,2));
    if(failures.length)process.exitCode=1;
  } finally { await browser?.close();await new Promise<void>(resolve=>server?server.close(()=>resolve()):resolve());if(fixtureDirectory)fs.rmSync(fixtureDirectory,{recursive:true}); }
}
main().catch(error=>{console.error(error);process.exitCode=1});
