const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const ts = require('typescript');
const esbuild = require('esbuild');
const root = path.resolve(__dirname, '../..');
const evidence = path.resolve(process.env.AVATAR_STATE_EVIDENCE || path.join(root, 'docs/materials/2026-10-04-controlled-avatar-generator/2026-10-05-intent-implementation'));

async function main() {
  const taskPath = path.join(root, 'src/lib/image-studio/tasks.ts');
  const ast = ts.createSourceFile(taskPath, fs.readFileSync(taskPath, 'utf8'), ts.ScriptTarget.Latest, true);
  const error = ast.statements.find(node => ts.isClassDeclaration(node) && node.name?.text === 'StudioError').getText(ast);
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sd2-avatar-intent-'));
  const records = new Map();
  const counters = { syntheticTextRequests: 0, syntheticImageSubmits: 0, productionDbWrites: 0, realPaidCalls: 0 };
  const description = '25-35岁女生，短发，不戴眼镜，不要胡须，自然沉稳';
  const raw = { summary: '希望是25至35岁的短发女生，不戴眼镜、不留胡须，气质自然沉稳。', explicit: { gender: { value: '女生', evidence: '女生' }, age: { value: '25-35', evidence: '25-35岁' }, hair_length: { value: '短发', evidence: '短发' }, glasses: { value: '不戴眼镜', evidence: '不戴眼镜' }, facial_hair: { value: '', excluded: ['胡须'], evidence: '不要胡须' } }, soft: { temperament: { value: '自然沉稳', evidence: '自然沉稳' } }, details: [], scopes: [], background: '', unrecognized: [], conflicts: [], clarifications: [] };
  global.__avatarIntentFixture = { records, counters, raw };
  const settings = `export async function getImageStudioSettings(){return {model:'gpt-image-2.5-sunburst',revision:24,prices:{'gpt-image-2.5-sunburst':5}}}`;
  const stubs = {
    '@/lib/prisma': `const rows=global.__avatarIntentFixture.records;const platformSetting={findUnique:async({where})=>rows.get(where.key)||null,create:async({data})=>{if(rows.has(data.key))throw Error('exists');rows.set(data.key,{...data});return data;},updateMany:async({where,data})=>{const row=rows.get(where.key);if(!row||row.value_json!==where.value_json)return {count:0};rows.set(where.key,{...row,...data});return {count:1};},upsert:async({where,create,update})=>{const next=rows.has(where.key)?{...rows.get(where.key),...update}:create;rows.set(where.key,next);return next;},findMany:async()=>[]};export const prisma={platformSetting,$transaction:async fn=>fn({platformSetting}),imageStudioTask:{findFirst:async()=>null},asset:{findFirst:async()=>null}};`,
    '@/lib/integrations/musk': `export class MuskApiError extends Error{};export async function getMuskApiSettings(){return {}};export function isMuskApiReady(){return true};export async function createMuskChatCompletion(){global.__avatarIntentFixture.counters.syntheticTextRequests++;return {content:JSON.stringify(global.__avatarIntentFixture.raw)}};`,
    '@/lib/image-studio/settings': settings,
    '@/lib/image-studio/tasks': `${error};export async function submitStudioBatch(owner,body){global.__avatarIntentFixture.counters.syntheticImageSubmits++;return 'synthetic-batch'};`,
    '@/lib/integrations/image-generation': `export async function getImageGenerationSettingsForModel(){return {provider:'fixture',supports_text_to_image:true,supports_image_to_image:true}};export function isImageGenerationApiReady(){return true};export function isStudioImageGenerationProvider(){return true};`,
    './store': `export const avatarKey=(owner,kind,id)=>owner+':'+kind+':'+id;export const avatarPlanKey=(owner,plan)=>avatarKey(owner,'plan',plan.id);export const avatarRecordKey=(owner,record)=>avatarKey(owner,'record',record.id);export async function readAvatar(owner,kind,id){const row=global.__avatarIntentFixture.records.get(avatarKey(owner,kind,id));return row?JSON.parse(row.value_json):null};`,
  };
  const bundle = await esbuild.build({entryPoints:['service','engine','description-parser','description-contract','catalog-metadata','intent'].map(name => path.join(root, `src/lib/avatar-random/${name}.ts`)),outdir:dir,bundle:true,platform:'node',format:'cjs',tsconfig:path.join(root,'tsconfig.json'),metafile:true,plugins:[{name:'local-only-api-boundaries',setup(build){build.onResolve({filter:/.*/},args=>Object.hasOwn(stubs,args.path)?{path:args.path,namespace:'fixture'}:null);build.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:stubs[args.path],loader:'ts'}));}}]});
  assert.ok(!Object.keys(bundle.metafile.inputs).some(input=>/src\/lib\/(prisma|credits|auth|integrations)\//.test(input)));
  const service = require(path.join(dir,'service.js'));
  const engine = require(path.join(dir,'engine.js'));
  const contract = require(path.join(dir,'description-contract.js'));
  const parser = require(path.join(dir,'description-parser.js'));
  const metadata = require(path.join(dir,'catalog-metadata.js'));
  const { avatarRulesSignature } = require(path.join(dir,'intent.js'));
  const cases = [];
  async function test(name, work) { try { await work(); cases.push({name,status:'PASS'}); } catch(error) { cases.push({name,status:'FAIL',error:error.message}); } }
  const base = {layout:'contact-sheet',description:'',choices:{},locks:{},intensity:'standard',people:1,candidates:4};
  let plan;
  await test('real prepare empty skips text model and quotes one image/four DNA',async()=>{plan=await service.prepareAvatarPlan('fixture-owner',{rules:base});assert.equal(counters.syntheticTextRequests,0);assert.equal(plan.candidates.length,4);assert.equal(plan.unitCredits,5);assert.ok(plan.sheetPrompt.includes('左上格'));assert.equal(new Set(plan.candidates.map(c=>c.characterId)).size,4);});
  await test('real prepare nonempty cannot implicitly buy analysis even if approved',async()=>{await assert.rejects(service.prepareAvatarPlan('fixture-owner',{rules:{...base,description},approveTextModel:true}),error=>error.parse?.state==='not-started');assert.equal(counters.syntheticTextRequests,0);});
  await test('one model response supplies summary, explicit, negative and soft; cache reused',async()=>{await service.parseAvatarDescription('fixture-owner',description,true);await service.parseAvatarDescription('fixture-owner',description,true);const status=await service.avatarDescriptionStatus('fixture-owner',description);assert.equal(status.state,'succeeded');assert.ok(status.understanding.summary.includes('女生'));assert.ok(status.understanding.explicit.some(s=>s.includes('排除')));assert.ok(status.understanding.soft.includes('气质：自然沉稳'));assert.equal(counters.syntheticTextRequests,1);});
  await test('analysis is account isolated and prepare requires matching parser binding',async()=>{const rules={...base,description};await assert.rejects(service.prepareAvatarPlan('another-owner',{rules}),error=>error.parse?.state==='not-started');await assert.rejects(service.prepareAvatarPlan('fixture-owner',{rules}),/文案分析已变化/);const status=await service.avatarDescriptionStatus('fixture-owner',description);plan=await service.prepareAvatarPlan('fixture-owner',{rules,descriptionId:status.descriptionId,parserVersion:status.parserVersion});assert.equal(counters.syntheticTextRequests,1);assert.ok(plan.candidates.every(c=>c.members[0].fields.gender.value==='女性'));});
  await test('semantic unresolved cache visible; repeated prepare/free recheck never calls model',async()=>{global.__avatarIntentFixture.raw={...raw,conflicts:['短发与长发需要选择']};const text=description+'，又要长发';await service.parseAvatarDescription('fixture-owner',text,true);const status=await service.avatarDescriptionStatus('fixture-owner',text);assert.equal(status.state,'needs-clarification');assert.ok(status.understanding.issues.length);const calls=counters.syntheticTextRequests;await service.parseAvatarDescription('fixture-owner',text,false,undefined,true);await assert.rejects(service.prepareAvatarPlan('fixture-owner',{rules:{...base,description:text}}),error=>error.parse?.state==='needs-clarification');assert.equal(counters.syntheticTextRequests,calls);});
  await test('description, choices, locks and image parameter edits reject old submitted quote',async()=>{for(const change of [{rules:{...plan.candidates[0].rules,description:'新文案'}},{rules:{...plan.candidates[0].rules,choices:{gender:'男性'}}},{rules:{...plan.candidates[0].rules,locks:{gender:{value:'男性',source:'user',locked:true}}}},{quality:'high'},{resolution:'2K'},{model:'different'}]){await assert.rejects(service.submitAvatarPlan('fixture-owner',plan.id,plan.layout,{rules:plan.candidates[0].rules,model:plan.model,quality:plan.quality,resolution:plan.resolution,...change}),/已变化/);}assert.equal(counters.syntheticImageSubmits,0);});
  await test('real submit exact matching draft remains one image task path',async()=>{await service.submitAvatarPlan('fixture-owner',plan.id,plan.layout,{rules:plan.candidates[0].rules,model:plan.model,quality:plan.quality,resolution:plan.resolution});assert.equal(counters.syntheticImageSubmits,1);});
  await test('aliases and generic facial-hair negation reach actual sampled DNA and prompt',async()=>{const parsed=contract.validateDescriptionConstraints(raw,description);for(let i=0;i<12;i++){const dna=engine.randomAvatar({...base,description},parsed,`intent-${i}`);assert.equal(dna.fields.facial_hair.value,'无胡须');assert.equal(dna.fields.glasses.value,'不戴眼镜');assert.equal(dna.fields.temperament.source,'inferred');assert.ok(Number(dna.fields.age.value)>=25&&Number(dna.fields.age.value)<=35);assert.ok(engine.compileAvatar([dna],parsed,false).prompt.includes('无胡须'));}});
  await test('explicit beard applies even for women/children; default random does not add it',async()=>{for(const gender of ['女性','男性']){const rules={...base,choices:{gender,age:'12'}};assert.equal(engine.randomAvatar(rules,engine.emptyConstraints(),'child').fields.facial_hair.value,'无胡须');const parsed=contract.validateDescriptionConstraints({...raw,soft:{},explicit:{facial_hair:{value:'络腮胡',evidence:'络腮胡'}}},'络腮胡');assert.equal(engine.randomAvatar(rules,parsed,'explicit-child').fields.facial_hair.value,'短络腮胡');}});
  await test('legacy missing new field compiles/requotes without mutating saved DNA',async()=>{const old=structuredClone(plan.candidates[0]);delete old.members[0].fields.facial_hair;delete old.members[0].catalogVersion;delete old.constraints.explicit.facial_hair;old.members[0].ruleVersion='1.0.0';const snapshot=JSON.stringify(old);engine.adaptAvatarPrompt(old,'gpt-image-2.5-sunburst');assert.equal(JSON.stringify(old),snapshot);const kept=engine.randomAvatar(old.rules,old.constraints,'styling',old.members[0],undefined,true);assert.equal(kept.fields.facial_hair,undefined);});
  await test('metadata covers every sampled field, stable value IDs/weights and truthful source restrictions',async()=>{const dna=plan.candidates[0].members[0];assert.deepEqual(Object.keys(metadata.catalogDefinitions).sort(),Object.keys(dna.fields).sort());for(const field of Object.values(metadata.catalogDefinitions)){assert.ok(field.definition&&field.promptTarget&&field.exclusions);assert.equal(new Set(field.values.map(v=>v.id)).size,field.values.length);assert.ok(field.values.every(v=>v.weight>0&&v.definition));}assert.ok(metadata.catalogSources.celeba.use.includes('excluded'));assert.ok(metadata.catalogSources.maad.license.includes('not imported'));assert.ok(metadata.seedGuarantee.includes('No cross-version'));});
  await test('unknown parser acceptance cannot retry a new request; saved receipt free recovery only',async()=>{const rows=new Map();let attempt=null,cache=null,calls=0;const store={readCache:async()=>cache,readAttempt:async()=>attempt,createAttempt:async next=>{attempt=next;return true;},replaceAttempt:async(expected,next)=>{if(expected!==attempt)return false;attempt=next;return true;},saveResponse:async(id,text)=>rows.set(id,text),readResponse:async id=>rows.get(id)??null,complete:async(expected,next,parsed)=>{if(expected!==attempt)return false;attempt=next;cache=parsed;return true;}};await assert.rejects(parser.resolveDescription(description,{approved:true},store,async()=>{calls++;throw Error('timeout');}));const status=await parser.inspectDescription(description,store);assert.equal(status.state,'unknown');assert.equal(status.retryToken,undefined);await assert.rejects(parser.resolveDescription(description,{approved:true,retryToken:'fake'},store,async()=>{calls++;return {content:JSON.stringify(raw)};}));assert.equal(calls,1);});
  await test('same description edits still invalidate quote; unordered object keys do not',async()=>{const rules=plan.candidates[0].rules;assert.notEqual(avatarRulesSignature({...rules,descriptionEditedAt:1}),avatarRulesSignature(rules));assert.equal(avatarRulesSignature({...rules,choices:{...rules.choices}}),avatarRulesSignature(rules));});
  const report = { version:require(path.join(root,'package.json')).version,scope:'real service/parser/contract/engine/compiler with controlled in-memory boundary adapters only',cases,passed:cases.filter(c=>c.status==='PASS').length,failed:cases.filter(c=>c.status==='FAIL').length,...counters,externalNetwork:'not present in loaded fixture modules',limitations:['Synthetic upstream requests and in-memory writes are not real paid acceptance or production DB evidence','submitStudioBatch billing/idempotency unchanged; existing evidence and source review used'] };
  fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(path.join(evidence,'intent-kernel-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
  delete global.__avatarIntentFixture;fs.rmSync(dir,{recursive:true,force:true});
  if(report.failed)throw Error(`${report.failed} intent scenarios failed`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
